apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: osrm-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: osrm-deployment
  minReplicas: 2
  maxReplicas: 6  
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
